#!/bin/bash

parts=''

for line in $(docker ps -a | grep $1);
do
	parts=($line)
	break
done

echo Attaching to ${parts[0]}

if [ $1 = 'wp-site' ]; then
    docker exec -it ${parts[0]} /bin/bash
else
    docker exec -it ${parts[0]} /bin/sh
fi
