version: '3'
services:
    db:
        container_name: wp-mysql
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wp_site

    adminer:
        depends_on:
            - db
        container_name: wp-adminer
        image: adminer:latest
        restart: always
        ports:
          - 8090:8080

    site:
        depends_on:
            - db
        container_name: wp-site
        image: nu-wp-site:latest
        volumes:
            - site-sync:/var/www/html:nocopy
        restart: always
        ports:
            - 80:80
        environment:
            WORDPRESS_DB_NAME: wp_site
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: wp_site
            WORDPRESS_DB_HOST: db:3306

    proxy:
        container_name: elb
        image: newstechnology/ssl-proxy:latest
        volumes:
            - ./volumes/certificates:/etc/nginx/certs
        ports:
            - 443:443
        environment:
            DOMAIN: localhost
            TARGET_HOST: site

    cache:
        container_name: wp-cache
        hostname: redis
        image: redis:alpine

    cache-ui:
        container_name: wp-cache-ui
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:cache:6379
        ports:
            - 8095:8081

volumes:
    db_data:
    site-sync:
        external: true
